(function(g){var window=this;var xGa=function(a,b){return g.Tb(a,b)},$5=function(a,b,c){a.C.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.ln(a.C,b,c)},yGa=function(a,b){var c=[];
g.cj(b,function(d){try{var e=g.Yn.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Xn(e)&&c.push(d)},a);
return c},zGa=function(a,b){var c=yGa(a,b);
g.Gb(c,function(d){g.Yn.prototype.remove.call(this,d)},a)},AGa=function(a){if(a.Xd){if(a.Xd.locationOverrideToken)return{locationOverrideToken:a.Xd.locationOverrideToken};
if(null!=a.Xd.latitudeE7&&null!=a.Xd.longitudeE7)return{latitudeE7:a.Xd.latitudeE7,longitudeE7:a.Xd.longitudeE7}}return null},BGa=function(a,b){g.nb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},CGa=function(a,b){var c=b instanceof g.Fc?b:g.Lc(b,/^data:image\//i.test(b));
a.src=g.Gc(c)},d6=function(){},DGa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},EGa=function(a){if(a.jf&&"function"==typeof a.jf)return a.jf();
if("string"===typeof a)return a.split("");if(g.Ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},FGa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ra(a)||"string"===typeof a)g.Gb(a,b,void 0);else{if(a.tg&&"function"==typeof a.tg)var c=a.tg();else if(a.jf&&"function"==typeof a.jf)c=void 0;else if(g.Ra(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=EGa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},GGa=function(a,b,c,d){var e=new g.Zm(null,void 0);
a&&g.$m(e,a);b&&g.an(e,b);c&&g.bn(e,c);d&&(e.B=d);return e},e6=function(a,b){g.Lo[a]=!0;
var c=g.Jo();c&&c.publish.apply(c,arguments);g.Lo[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Wm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",HGa(this,a.capabilities||""),IGa(this,a.experiments||""))},HGa=function(a,b){a.capabilities.clear();
g.Ke(b.split(","),g.Wa(xGa,JGa)).forEach(function(c){a.capabilities.add(c)})},IGa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},KGa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},LGa=function(a){return new g6(a)},MGa=function(a){return Array.isArray(a)?g.Pc(a,LGa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+g.Pc(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},NGa=function(a){return g.Pc(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.jb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.jb(a,function(c){return h6(c,b)})},OGa=function(){var a=(0,g.Ns)();
a&&zGa(a,a.u.Mi(!0))},n6=function(){var a=g.Qs("yt-remote-connected-devices")||[];
g.Cb(a);return a},PGa=function(a){if(g.ob(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Pc(a,function(d,e){return 0==e?d:d.substring(c.length)})},QGa=function(a){g.Ps("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.Qs("yt-remote-device-id");a||(a=k6(),g.Ps("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.nb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.nb(a,b);g.Vs()&&g.Fb(a,b);a=PGa(a);if(g.ob(a))try{g.xq("remote_sid")}catch(c){}else try{g.vq("remote_sid",a.join(","),-1)}catch(c){}},RGa=function(){return g.Qs("yt-remote-session-browser-channel")},SGa=function(){return g.Qs("yt-remote-local-screens")||[]},TGa=function(){g.Ps("yt-remote-lounge-token-expiration",!0,86400)},UGa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Pc(SGa(),function(d){return d.loungeToken}),c=g.Pc(a,function(d){return d.loungeToken});
g.jh(c,function(d){return!g.nb(b,d)})&&TGa();
g.Ps("yt-remote-local-screens",a,31536E3)},VGa=function(a,b){g.Ps("yt-remote-session-browser-channel",a);
g.Ps("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.nb(c,d)||c.push(d);QGa(c);q6()},r6=function(a){a||(g.Rs("yt-remote-session-screen-id"),g.Rs("yt-remote-session-video-id"));
q6();a=n6();g.rb(a,p6());QGa(a)},WGa=function(){if(!s6){var a=g.io();
a&&(s6=new g.Sn(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},XGa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},YGa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?ZGa(a.shift(),function(){t6(a)}):u6()},$Ga=function(a){return"chrome-extension://"+a+"/cast_sender.js"},ZGa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.jd(d,g.ng(a));(document.head||document.documentElement).appendChild(d)},u6=function(){var a=YGa();
a&&a(!1,"No cast extension found")},bHa=function(){if(aHa){var a=2,b=YGa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ZGa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},cHa=function(){bHa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.B.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.We=b;this.F=(0,g.z)(this.QI,this);this.u=!1;this.B=0;this.C=this.Ua=null;this.D=[]},w6=function(a,b,c){g.B.call(this);
this.D=null!=c?a.bind(c):a;this.We=b;this.C=null;this.u=!1;this.B=0;this.Ua=null},x6=function(a){a.Ua=g.Um(function(){a.Ua=null;
a.u&&!a.B&&(a.u=!1,x6(a))},a.We);
var b=a.C;a.C=null;a.D.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return DGa(a)},z6=function(){},A6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},C6=function(a){B6.dispatchEvent(new dHa(B6,a))},dHa=function(a){g.Ll.call(this,"statevent",a)},D6=function(){},eHa=function(){},gHa=function(a){return(a=fHa(a))?new ActiveXObject(a):new XMLHttpRequest},fHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},E6=function(a,b,c,d){this.u=a;
this.B=b;this.P=c;this.K=d||1;this.F=45E3;this.D=new g.V0(this);this.C=new g.Tm;this.C.setInterval(250)},iHa=function(a,b,c){a.On=1;
a.Mj=a6(b.clone());a.Vl=c;a.I=!0;hHa(a,null)},F6=function(a,b,c,d,e){a.On=1;
a.Mj=a6(b.clone());a.Vl=null;a.I=c;e&&(a.NF=!1);hHa(a,d)},hHa=function(a,b){a.Hn=g.A();
G6(a);a.Ck=a.Mj.clone();b6(a.Ck,"t",a.K);a.Eq=0;a.Zd=a.u.Rv(a.u.kq()?b:null);0<a.Gw&&(a.Tt=new w6((0,g.z)(a.MG,a,a.Zd),a.Gw));a.D.ua(a.Zd,"readystatechange",a.nQ);var c=a.xl?g.Zb(a.xl):{};a.Vl?(a.Bu="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Zd.send(a.Ck,a.Bu,a.Vl,c)):(a.Bu="GET",a.NF&&!g.Ae&&(c.Connection="close"),a.Zd.send(a.Ck,a.Bu,null,c));a.u.rh(1)},lHa=function(a,b,c){for(var d=!0;!a.Yk&&a.Eq<c.length;){var e=jHa(a,c);
if(e==H6){4==b&&(a.bk=4,C6(15),d=!1);break}else if(e==kHa){a.bk=4;C6(16);d=!1;break}else I6(a,e)}4==b&&0==c.length&&(a.bk=1,C6(17),d=!1);a.Ch=a.Ch&&d;d||(J6(a),K6(a))},jHa=function(a,b){var c=a.Eq,d=b.indexOf("\n",c);
if(-1==d)return H6;c=Number(b.substring(c,d));if(isNaN(c))return kHa;d+=1;if(d+c>b.length)return H6;var e=b.substr(d,c);a.Eq=d+c;return e},oHa=function(a,b){a.Hn=g.A();
G6(a);var c=b?window.location.hostname:"";a.Ck=a.Mj.clone();$5(a.Ck,"DOMAIN",c);$5(a.Ck,"t",a.K);try{a.Hh=new ActiveXObject("htmlfile")}catch(n){J6(a);a.bk=7;C6(22);K6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in L6)h=L6[h];else if(h in nHa)h=L6[h]=nHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
L6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.gd(g.kc("b/12014412"),d+"</body></html>");a.Hh.open();a.Hh.write(g.cd(c));a.Hh.close();a.Hh.parentWindow.m=(0,g.z)(a.BP,a);a.Hh.parentWindow.d=(0,g.z)(a.NE,a,!0);a.Hh.parentWindow.rpcClose=(0,g.z)(a.NE,a,!1);c=a.Hh.createElement("DIV");a.Hh.parentWindow.document.body.appendChild(c);d=g.Kc(a.Ck.toString());d=g.nd(g.Gc(d));d=g.gd(g.kc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,d);a.u.rh(1)},G6=function(a){a.pz=g.A()+a.F;
pHa(a,a.F)},pHa=function(a,b){if(null!=a.Un)throw Error("WatchDog timer not null");
a.Un=A6((0,g.z)(a.NP,a),b)},M6=function(a){a.Un&&(g.v.clearTimeout(a.Un),a.Un=null)},K6=function(a){a.u.SB()||a.Yk||a.u.gs(a)},J6=function(a){M6(a);
g.eg(a.Tt);a.Tt=null;a.C.stop();g.sAa(a.D);if(a.Zd){var b=a.Zd;a.Zd=null;b.abort();b.dispose()}a.Hh&&(a.Hh=null)},I6=function(a,b){try{a.u.FE(a,b),a.u.rh(4)}catch(c){}},rHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;qHa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){rHa(a,b,c,d,f)},f)})}},qHa=function(a,b,c){var d=new Image;
d.onload=function(){try{N6(d),c(!0)}catch(e){}};
d.onerror=function(){try{N6(d),c(!1)}catch(e){}};
d.onabort=function(){try{N6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{N6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
CGa(d,a)},N6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},O6=function(a){g.im.call(this);
this.headers=new g.Wm;this.ba=a||null;this.B=!1;this.Y=this.u=null;this.ra=this.N="";this.I=0;this.D="";this.F=this.ha=this.P=this.fa=!1;this.K=0;this.V=null;this.za="";this.X=this.da=!1},sHa=function(a){return g.ye&&g.$d(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},tHa=function(a){return"content-type"==a.toLowerCase()},vHa=function(a,b){a.B=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;uHa(a);P6(a)},uHa=function(a){a.fa||(a.fa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},xHa=function(a){if(a.B&&"undefined"!=typeof g.$0)if(a.Y[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.P&&4==Q6(a))g.Um(a.BE,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.xd(1,String(a.N));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!wHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<Q6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";uHa(a)}}finally{P6(a)}}},P6=function(a,b){if(a.u){yHa(a);
var c=a.u,d=a.Y[0]?g.Oa:null;a.u=null;a.Y=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},yHa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.V&&(g.v.clearTimeout(a.V),a.V=null)},Q6=function(a){return a.u?a.u.readyState:0},S6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.ra+" "+a.N+" "+a.getStatus()+"]"},zHa=function(a){this.u=a;
this.B=new z6},AHa=function(a){var b=T6(a.u,a.po,"/mail/images/cleardot.gif");
a6(b);rHa(b.toString(),5E3,(0,g.z)(a.PH,a),3,2E3);a.rh(1)},V6=function(a){var b=a.u.P;
if(null!=b)C6(5),b?(C6(11),U6(a.u,a,!1)):(C6(12),U6(a.u,a,!0));else if(a.Qf=new E6(a,void 0,void 0,void 0),a.Qf.xl=a.Ew,b=a.u,b=T6(b,b.kq()?a.Uo:null,a.Fw),C6(5),!g.ye||g.ae(10))b6(b,"TYPE","xmlhttp"),F6(a.Qf,b,!1,a.Uo,!1);else{b6(b,"TYPE","html");var c=a.Qf;a=!!a.Uo;c.On=3;c.Mj=a6(b.clone());oHa(c,a)}},W6=function(a,b,c){this.Da=1;
this.u=[];this.C=[];this.D=new z6;this.K=a||null;this.P=null!=b?b:null;this.F=c||!1},BHa=function(a,b){this.u=a;
this.map=b;this.context=null},CHa=function(a,b,c,d){g.Ll.call(this,"timingevent",a);
this.size=b;this.bq=d},DHa=function(a){g.Ll.call(this,"serverreachability",a)},GHa=function(a){EHa(a);
if(3==a.Da){var b=a.Gp++,c=a.Gr.clone();$5(c,"SID",a.B);$5(c,"RID",b);$5(c,"TYPE","terminate");X6(a,c);b=new E6(a,a.B,b,void 0);b.On=2;b.Mj=a6(c.clone());CGa(new Image,b.Mj.toString());b.Hn=g.A();G6(b)}FHa(a)},HHa=function(a){a.lI(1,0);
a.Gr=T6(a,null,a.Dw);Y6(a)},EHa=function(a){a.Qj&&(a.Qj.abort(),a.Qj=null);
a.wd&&(a.wd.cancel(),a.wd=null);a.Oi&&(g.v.clearTimeout(a.Oi),a.Oi=null);Z6(a);a.Gf&&(a.Gf.cancel(),a.Gf=null);a.Uj&&(g.v.clearTimeout(a.Uj),a.Uj=null)},IHa=function(a,b){if(0==a.Da)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new BHa(a.hM++,b));2!=a.Da&&3!=a.Da||Y6(a)},Y6=function(a){a.Gf||a.Uj||(a.Uj=A6((0,g.z)(a.ME,a),0),a.Km=0)},KHa=function(a,b){if(1==a.Da){if(!b){a.Gp=Math.floor(1E5*Math.random());
var c=a.Gp++,d=new E6(a,"",c,void 0);d.xl=a.Pm;var e=$6(a),f=a.Gr.clone();$5(f,"RID",c);$5(f,"CVER","1");X6(a,f);iHa(d,f,e);a.Gf=d;a.Da=2}}else 3==a.Da&&(b?JHa(a,b):0==a.u.length||a.Gf||JHa(a))},JHa=function(a,b){if(b)if(6<a.Zk){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Gp-1;var d=$6(a)}else c=b.P,d=b.Vl;else c=a.Gp++,d=$6(a);var e=a.Gr.clone();$5(e,"SID",a.B);$5(e,"RID",c);$5(e,"AID",a.an);X6(a,e);c=new E6(a,a.B,c,a.Km+1);c.xl=a.Pm;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Gf=c;iHa(c,e,d)},X6=function(a,b){if(a.Se){var c=a.Se.tB();
c&&g.Jb(c,function(d,e){$5(b,e,d)})}},$6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Zk&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={pm:e.pm},f++){e.pm=a.u[f].u;var h=a.u[f].map;e.pm=6>=a.Zk?f:e.pm-d;try{g.Jb(h,function(l){return function(m,n){c.push("req"+l.pm+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.pm+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},LHa=function(a){a.wd||a.Oi||(a.I=1,a.Oi=A6((0,g.z)(a.LE,a),0),a.tm=0)},a7=function(a){if(a.wd||a.Oi||3<=a.tm)return!1;
a.I++;a.Oi=A6((0,g.z)(a.LE,a),MHa(a,a.tm));a.tm++;return!0},U6=function(a,b,c){a.zu=c;
a.ai=b.cj;a.F||HHa(a)},Z6=function(a){null!=a.il&&(g.v.clearTimeout(a.il),a.il=null)},MHa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},b7=function(a,b){if(2==b||9==b){var c=null;
a.Se&&(c=null);var d=(0,g.z)(a.TQ,a);c||(c=new g.Zm("//www.google.com/images/cleardot.gif"),a6(c));qHa(c.toString(),1E4,d)}else C6(2);NHa(a,b)},NHa=function(a,b){a.Da=0;
a.Se&&a.Se.HA(b);FHa(a);EHa(a)},FHa=function(a){a.Da=0;
a.ai=-1;if(a.Se)if(0==a.C.length&&0==a.u.length)a.Se.Fv();else{g.ub(a.C);var b=g.ub(a.u);a.C.length=0;a.u.length=0;a.Se.Fv(b)}},T6=function(a,b,c){var d=g.gn(c);
if(""!=d.u)b&&g.an(d,b+"."+d.u),g.bn(d,d.D);else{var e=window.location;d=GGa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Io&&g.Jb(a.Io,function(f,h){$5(d,h,f)});
$5(d,"VER",a.Zk);X6(a,d);return d},OHa=function(){},PHa=function(){this.u=[];
this.B=[]},QHa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.B.call(this);
this.u=new g.H(this.uP,0,this);g.C(this,this.u);this.We=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.V=a;this.I=b;this.C=new g.Rn;this.B=new c7(this.zQ,this);this.u=null;this.Ld=!1;this.F=null;this.N="";this.P=this.D=0;this.K=[];this.Y=c;this.X=d},RHa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.zu,sessionId:a.u.B,arrayId:a.u.an}},SHa=function(a,b){a.P=b||0;
a.B.stop();e7(a);a.u&&(3==a.u.Da&&KHa(a.u),GHa(a.u));a.P=0},f7=function(a){return!!a.u&&3==a.u.Da},e7=function(a){if(a.u){var b=a.X(),c=a.u.Pm||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Pm=c}},THa=function(a,b){(a.I.loungeIdToken=b)||a.B.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.xd(4,a))||"";b&&(this.port=":"+b);this.domain=g.yd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Dc(a,"10.0")&&(this.B=!1))},h7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Ld(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Wa(a.D,d,!0),onError:g.Wa(a.C,e),Lf:g.Wa(a.F,e)};c&&(a.Zb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.oq(b,a)},XHa=function(){var a=UHa;
VHa();j7.push(a);WHa(j7)},k7=function(a,b){VHa();
var c=j7,d=YHa(a,String(b));g.ob(c)?ZHa(d):(WHa(c),g.Gb(c,function(e){e(d)}))},VHa=function(){j7||(j7=g.Na("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",j7,void 0))},ZHa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},WHa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];g.Gb(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},YHa=function(a,b){var c=(g.A()-$Ha)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.P.call(this);
this.I=a;this.screens=[]},aIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},bIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ke(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=aIa(a,b[d])||c;return c},cIa=function(a,b){var c=a.screens.length;
a.screens=g.Ke(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.P.call(this);
this.I=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Ua=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},dIa=function(a){if(a.screens.length){var b=g.Pc(a.screens,function(d){return d.id}),c=h7(a.B,"/pairing/get_lounge_token_batch");
i7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.ZI,a),(0,g.z)(a.YI,a))}},q7=function(a){if(g.uo("deprecate_pair_servlet_enabled"))return bIa(a,[]);
var b=MGa(SGa());b=g.Ke(b,function(c){return!c.uuid});
return bIa(a,b)},s7=function(a,b){UGa(g.Pc(a.screens,KGa));
b&&TGa()},u7=function(a,b){g.P.call(this);
this.I=b;var c=g.Qs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.nb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;t7("Initialized with "+g.Fj(this.u))},eIa=function(a,b,c){var d=h7(a.F,"/pairing/get_screen_availability");
i7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.u))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Fj(a.u)),a.u=b,a.W("screenChange"));fIa(a)},w7=function(a){isNaN(a.C)||g.Ho(a.C);
a.C=g.Fo((0,g.z)(a.qy,a),0<a.D&&a.D<g.A()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},gIa=function(a){var b={};
g.Gb(a.I(),function(c){c.token?b[c.token]=c.id:this.Xc("Requesting availability of screen w/o lounge token.")});
return b},fIa=function(a){a=g.Qb(g.Kb(a.u,function(b){return b}));
g.Cb(a);a.length?g.Ps("yt-remote-online-screen-ids",a.join(","),60):g.Rs("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};hIa(this)},jIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Xf();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);eIa(a.u,l,function(m){e(m?l:null)})}else c?iIa(a,c,(0,g.z)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));eIa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},kIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},iIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Zb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.oq(h7(a.F,"/pairing/get_lounge_token_batch"),e)},lIa=function(a){a.screens=a.B.Xf();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},hIa=function(a){z7(a);
a.B=new r7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.gJ,a));lIa(a);a.C=MGa(g.Qs("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.C));a.u=new u7(a.F,(0,g.z)(a.Xf,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.W("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.Ps("yt-remote-automatic-screen-cache",g.Pc(a.C,KGa)));z7(a);a.D[b.uuid]=b.id;g.Ps("yt-remote-device-id-map",a.D,31536E3);return b},z7=function(a){a.D=g.Qs("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.P.call(this);
this.Y=c;this.P=a;this.u=b;this.K=null},B7=function(a,b){k7(a.Y,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.CR,this);this.D=(0,g.z)(this.UP,this);this.C=g.Fo((0,g.z)(function(){mIa(this,null)},this),12E4)},nIa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Fj(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Oa,(0,g.z)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Fj(b))},mIa=function(a,b){g.Ho(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.Jt,a),d=(0,g.z)(a.fg,a);a.LB(b,c,d,5)}}else a.fg(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.C=this.I=null;this.N="";this.ba=c;this.V=null;this.F=g.Oa;this.D=NaN;this.X=(0,g.z)(this.FR,this);this.B=g.Oa},oIa=function(a){a.B=a.P.UG(a.N,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Oa;
this.Jt(b)},a),(0,g.z)(function(b){this.B=g.Oa;
this.fg(b)},a))},pIa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.ba;WGa()&&(b.env_useStageMdx=1);return g.Hd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.B=g.Fo((0,g.z)(this.bn,this,null),150)},F7=function(a,b,c,d){g.P.call(this);
this.B=a;this.K=b||"233637DE";this.I=c||"cl";this.P=d||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.LO,this)},qIa=function(a,b){return b?g.jb(a.C,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},UHa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.F||!!a.C.length||!!a.u},I7=function(a,b,c){b!=a.u&&(g.eg(a.u),(a.u=b)?(c?a.W("yt-remote-cast2-receiver-resumed",b.u):a.W("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.JE,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.bn(null)):a.W("yt-remote-cast2-session-change",null))},rIa=function(a){var b=a.B.TG(),c=a.u&&a.u.u;
a=g.Pc(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=qIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},xIa=function(a,b,c,d,e,f,h){sIa()?tIa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?uIa(a,c):(window.__onGCastApiAvailable=function(l,m){l?uIa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.Rs("yt-remote-cast-available"),g.Rs("yt-remote-cast-receiver"),vIa(),c(!1))},d?g.So("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?cHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(bHa(),t6(wIa.map($Ga))))):J7("Cannot initialize because not running Chrome")},vIa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);yIa(!1);g.Oo(O7);O7.length=0},P7=function(){return!!g.Qs("yt-remote-cast-installed")},zIa=function(){var a=g.Qs("yt-remote-cast-receiver");
return a?a.friendlyName:null},AIa=function(){J7("clearCurrentReceiver");
g.Rs("yt-remote-cast-receiver")},BIa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.No("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},sIa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.bB||a},CIa=function(a,b){N7().init(a,b)},tIa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ps("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.Ps("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.Ps("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.Rs("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Na("yt.mdx.remote.cloudview.instance_")},uIa=function(a,b){M7(!0);
K7(!1);CIa(a,function(c){c?(yIa(!0),g.Po("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.Rs("yt-remote-cast-available"),g.Rs("yt-remote-cast-receiver"),vIa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.Ps("yt-remote-cast-installed",a)},Q7=function(){return!!g.Na("yt.mdx.remote.cloudview.apiReady_")},yIa=function(a){J7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.u=null;this.hasNext=this.bi=!1;this.N=this.P=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.bi=!1;a.hasNext=!1;a.K=0;a.I=g.A();a.F=0;a.B=0;a.P=0;a.N=0;a.D=NaN;a.C=!1},V7=function(a){return a.Eb()?(g.A()-a.I)/1E3:0},W7=function(a,b){a.K=b;
a.I=g.A()},X7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.u);b.hasPrevious=a.bi;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.P;b.loadedTime=a.N;b.liveIngestionTime=a.D;return b},a8=function(a,b){g.P.call(this);
this.Da=0;this.C=a;this.F=[];this.D=new PHa;this.B=this.u=null;this.P=(0,g.z)(this.WM,this);this.I=(0,g.z)(this.Ip,this);this.K=(0,g.z)(this.VM,this);this.N=(0,g.z)(this.eN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.sz,this),DIa(this))):c=3;0!=c&&(b?this.sz(c):g.Fo((0,g.z)(function(){this.sz(c)},this),0));
var d=BIa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.C.getPlayerContextData())},DIa=function(a){g.Gb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Wa(this.HO,b),this))},a)},EIa=function(a){g.Gb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){EIa(a);
a.C.setPlayerContextData(Z7(b));DIa(a)},$7=function(a,b){a.B&&(a.B.removeUpdateListener(a.P),a.B.removeMediaListener(a.I),a.Ip(null));
a.B=b;a.B&&(k7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.P),a.B.addMediaListener(a.I),a.B.media.length&&a.Ip(a.B.media[0]))},FIa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.Xc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Xc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.P.call(this);
this.F=NaN;this.X=!1;this.P=this.K=this.N=this.V=NaN;this.Y=[];this.D=this.I=this.C=this.Cb=this.u=null;this.fa=a;this.Y.push(g.cp(window,"beforeunload",(0,g.z)(this.SI,this)));this.B=[];this.Cb=new T7;this.ba=b.id;this.u=GIa(this,c);this.u.subscribe("handlerOpened",this.aN,this);this.u.subscribe("handlerClosed",this.XM,this);this.u.subscribe("handlerError",this.YM,this);this.u.subscribe("handlerMessage",this.ZM,this);THa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Cb.videoId;
g.Vs()&&g.Ps("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},GIa=function(a,b){return new d7(h7(a.fa,"/bc"),b,!1,function(){return a.PG()})},j8=function(a,b){a.W("proxyStateChange",b)},HIa=function(a){a.F=g.Fo((0,g.z)(function(){i8("Connecting timeout");
this.Fm(1)},a),2E4)},k8=function(a){g.Ho(a.F);
a.F=NaN},l8=function(a){g.Ho(a.V);
a.V=NaN},IIa=function(a){m8(a);
a.N=g.Fo((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Ho(a.N);
a.N=NaN},KIa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.u)&&isNaN(a.F))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.JB()&&a.Cb.reset(),j8(a,1),n8(a,"getNowPlaying"),JIa(a)):a.Fm(1)},LIa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Cb.videoId&&(g.Wb(b.params)?a.Cb.u=null:a.Cb.u=b.params,a.W("remotePlayerChange"))},MIa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Cb.listId=b.params.listId||a.Cb.listId;Y7(a.Cb,c,d);a.W("remoteQueueChange")},OIa=function(a,b){b.params=b.params||{};
MIa(a,b);NIa(a,b);a.W("autoplayDismissed")},NIa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.Cb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Cb.playerState&&(c=-1E3);a.Cb.playerState=c;c=Number(b.params.loadedTime);a.Cb.N=isNaN(c)?0:c;c=Number(b.params.duration);a.Cb.P=isNaN(c)?0:c;c=a.Cb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Cb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Cb.playerState?IIa(a):m8(a);a.W("remotePlayerChange")},PIa=function(a,b){if(-1E3!=
a.Cb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Cb.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.Cb,isNaN(c)?0:c);a.W("remotePlayerChange")}},QIa=function(a,b){var c="true"==b.params.muted;
a.Cb.volume=parseInt(b.params.volume,10);a.Cb.muted=c;a.W("remotePlayerChange")},RIa=function(a,b){a.I=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},SIa=function(a,b){var c="true"==b.params.hasNext;
a.Cb.bi="true"==b.params.hasPrevious;a.Cb.hasNext=c;a.W("previousNextChange")},JIa=function(a){g.Ho(a.P);
a.P=g.Fo((0,g.z)(a.Fm,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Fj(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Ue=a;this.u=[];this.u.push(this.Ue.$_s("screenChange",(0,g.z)(this.AR,this)));this.u.push(this.Ue.$_s("onlineScreenChange",(0,g.z)(this.nO,this)))},XIa=function(a,b){b=g.L("MDX_CONFIG")||b;
OGa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),WGa()&&(p8.u="/api/loungedev"));q8||(q8=g.Na("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",q8,void 0));TIa();var c=r8();if(!c){var d=new x7(p8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);xIa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.Na("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Fj(b)),u8.push(g.No("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.No("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.No("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.No("yt-remote-cast2-session-change",UIa)),u8.push(g.No("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),AIa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.uo("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.Fj(e)),VIa(e),c.start(),s8()||WIa())},ZIa=function(){var a=YIa();
P7()&&g.Qs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},YIa=function(){var a=r8().Ue.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return NGa(a)},A8=function(){var a=$Ia();
!a&&P7()&&zIa()&&(a={key:"cast-selector-receiver",name:zIa()});return a},$Ia=function(){var a=YIa(),b=y8();
b||(b=w8());return g.jb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Xf();return m6(b,a)},UIa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Na("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Na("yt.mdx.remote.currentScreenId_")},aJa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},bJa=function(){return g.Na("yt.mdx.remote.connectData_")},v8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Na("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||aJa("");g.Ia("yt.mdx.remote.connection_",a,void 0);q8&&(g.Gb(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.Vs();
if(!a)return null;var b=r8();if(!b)return null;b=b.Xf();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{aJa(a.id);var c=new h8(p8,a,x8());c.connect(b,bJa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},WIa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),AIa(),t8("Skipping connecting because no session screen found."))},TIa=function(){var a=x8();
if(g.Wb(a)){a=p6();var b=g.Qs("yt-remote-session-name")||"",c=g.Qs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Na("yt.mdx.remote.channelParams_")||{}},VIa=function(a){a?(g.Ps("yt-remote-session-app",a.app),g.Ps("yt-remote-session-name",a.name)):(g.Rs("yt-remote-session-app"),g.Rs("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.B=a;this.J=b;this.sb=c;this.events=new g.Sr(this);this.V=this.events.R(this.J,"onVolumeChange",this.lE);this.F=!1;this.suggestion=null;this.I=new g.XK(64);this.u=new g.H(this.XF,500,this);this.C=new g.H(this.YF,1E3,this);this.P=new v6(this.fR,0,this);this.D={};this.N=new g.H(this.AG,1E3,this);this.K=new w6(this.seekTo,1E3,this);this.X=g.Oa;g.C(this,this.events);this.events.R(b,"onCaptionsTrackListChanged",this.QN);this.events.R(b,"captionschanged",this.TM);this.events.R(b,"captionssettingschanged",
this.bG);this.events.R(b,"videoplayerreset",this.Kt);this.events.R(b,"mdxautoplaycancel",function(){d.sb.aB()});
a=this.sb;a.la();a.subscribe("proxyStateChange",this.EE,this);a.subscribe("remotePlayerChange",this.Np,this);a.subscribe("remoteQueueChange",this.Kt,this);a.subscribe("previousNextChange",this.AE,this);a.subscribe("nowAutoplaying",this.vE,this);a.subscribe("autoplayDismissed",this.WD,this);g.C(this,this.u);g.C(this,this.C);g.C(this,this.P);g.C(this,this.N);g.C(this,this.K);this.bG();this.Kt();this.Np()},cJa=function(a){a.Fc(0);
a.u.stop();a.Jd(new g.XK(64))},K8=function(a,b){if(J8(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.bc(c,b));a.sb.QG(a.J.getVideoData(1).videoId,c);a.D=b8(a.sb).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.sb.playVideo(c.videoId,b,d,e,c.playerParams,c.wg,AGa(c));a.Jd(new g.XK(1))},dJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{iC:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return b8(a.sb).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"\u0421\u043a\u043e\u0440\u043e \u0432\u0430\u043c \u043d\u0435 \u043f\u0440\u0438\u0434\u0435\u0442\u0441\u044f \u0432\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043e\u0434, \u0447\u0442\u043e\u0431\u044b \u0441\u0432\u044f\u0437\u0430\u0442\u044c \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0441 \u0442\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440\u043e\u043c."},
{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435..."},{G:"button",ia:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Z:"\u041e\u041a"}]}]}]});this.u=new g.GN(this,250);this.learnMoreButton=this.ga("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ga("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.u);this.R(this.learnMoreButton,"click",this.B);this.R(this.okButton,
"click",this.C)},N8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-popup-title",Z:"\u0412\u044b \u0432\u044b\u0448\u043b\u0438 \u0438\u0437 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430"},{G:"div",L:"ytp-mdx-popup-description",Z:'\u0420\u043e\u043b\u0438\u043a\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0432\u044b \u043f\u043e\u0441\u043c\u043e\u0442\u0440\u0438\u0442\u0435, \u043c\u043e\u0433\u0443\u0442 \u0431\u044b\u0442\u044c \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u044b \u0432 \u0438\u0441\u0442\u043e\u0440\u0438\u044e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u0442\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440\u0435, \u0447\u0442\u043e \u0441\u043a\u0430\u0436\u0435\u0442\u0441\u044f \u043d\u0430 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f\u0445. \u0427\u0442\u043e\u0431\u044b \u044d\u0442\u043e\u0433\u043e \u0438\u0437\u0431\u0435\u0436\u0430\u0442\u044c, \u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 "\u041e\u0442\u043c\u0435\u043d\u0430" \u0438 \u0432\u043e\u0439\u0434\u0438\u0442\u0435 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435.'},
{G:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-cancel"],Z:"\u041e\u0442\u043c\u0435\u043d\u0430"},{G:"button",ia:["ytp-button","ytp-mdx-privacy-popup-confirm"],Z:"\u041e\u041a"}]}]}]});this.u=new g.GN(this,250);this.cancelButton=this.ga("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ga("ytp-mdx-privacy-popup-confirm");g.C(this,this.u);this.R(this.cancelButton,"click",this.B);this.R(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,
{G:"div",
L:"ytp-remote",S:[{G:"div",L:"ytp-remote-display-status",S:[{G:"div",L:"ytp-remote-display-status-icon",S:[g.$M()]},{G:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.GN(this,250);g.C(this,this.u);this.R(a,"presentingplayerstatechange",this.B);eJa(this,g.jI(a))},eJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.gJ('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):b.Eb()||g.T(b,4)?g.gJ('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.gJ('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.wa("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.HZ.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.J=a;this.Bk={};this.R(a,"onMdxReceiversChange",this.D);this.R(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.sS.call(this,a);
this.kh={key:k6(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.Oh=null;this.subscriptions=[];this.Zx=this.sb=null;this.Bk=[this.kh];this.Sj=this.kh;this.Ac=new g.XK(64);this.CC=0;this.ie=-1;this.dn=null;this.Pp=this.Ps=!1;this.Ul=this.Dn=null;if(!g.ZB(this.player.T())){a=this.player;var b=g.FW(a);b&&(b=b.ul())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.mP(a,b.element,4);this.Dn=new N8;g.C(this,this.Dn);g.mP(a,this.Dn.element,4);g.R(this.player.T().experiments,
"pair_servlet_deprecation_warning_enabled")&&!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.dn=new M8,g.C(this,this.dn),g.mP(a,this.dn.element,4));this.Pp=!!w8();this.Ps=!!g.Qs("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.Ul&&(a.player.removeEventListener("presentingplayerstatechange",a.Ul),a.Ul=null)},fJa=function(a,b,c){a.Ac=c;
a.player.W("presentingplayerstatechange",new g.tI(c,b))},gJa=function(a,b,c){var d=!1;
1===b?d=!a.Pp:2===b&&(d=!a.Ps);d&&g.vI(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.Sj.key)if(b.key===a.kh.key)B8();
else{if(a.dn&&!a.Ps&&b!==a.kh&&"cast-selector-receiver"!==b.key&&g.iC(a.player.T()))hJa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Pp||!a.Dn);(c?0:g.iC(a.player.T())||g.mC(a.player.T()))&&iJa(a)}a.Sj=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ka(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.wg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=AGa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Fj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Xf(),(c=m6(c,b.key))&&C8(c,1))}},iJa=function(a){g.jI(a.player).Eb()?a.player.pauseVideo():(a.Ul=function(b){gJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Ul));
a.Dn&&a.Dn.qc();z8()||(G8=!0)},hJa=function(a){g.jI(a.player).Eb()?a.player.pauseVideo():(a.Ul=function(b){gJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Ul));
a.dn&&a.dn.qc();z8()||(G8=!0)},nHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},L6={"'":"\\'"},jJa={},JGa={gS:"atp",eV:"ska",PU:"que",gU:"mus",dV:"sus",fT:"dsp",WU:"seq"},s6,o6="",aHa=XGa("loadCastFramework")||XGa("loadCastApplicationFramework"),wIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ya(v6,g.B);g.k=v6.prototype;g.k.OI=function(a){this.D=arguments;this.u=!1;this.Ua?this.C=g.A()+this.We:this.Ua=g.Um(this.F,this.We)};
g.k.stop=function(){this.Ua&&(g.v.clearTimeout(this.Ua),this.Ua=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.aa=function(){this.stop();v6.gd.aa.call(this)};
g.k.QI=function(){this.C?(this.Ua=g.Um(this.F,this.C-g.A()),this.C=null):(this.Ua=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(w6,g.B);g.k=w6.prototype;g.k.SC=function(a){this.C=arguments;this.Ua||this.B?this.u=!0:x6(this)};
g.k.stop=function(){this.Ua&&(g.v.clearTimeout(this.Ua),this.Ua=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Ua||(this.u=!1,x6(this))};
g.k.aa=function(){g.B.prototype.aa.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var B6=new g.im;g.u(dHa,g.Ll);D6.prototype.u=null;D6.prototype.getOptions=function(){var a;(a=this.u)||(a={},fHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Ya(eHa,D6);T8=new eHa;g.k=E6.prototype;g.k.xl=null;g.k.Ch=!1;g.k.Un=null;g.k.pz=null;g.k.Hn=null;g.k.On=null;g.k.Mj=null;g.k.Ck=null;g.k.Vl=null;g.k.Zd=null;g.k.Eq=0;g.k.Hh=null;g.k.Bu=null;g.k.bk=null;g.k.Vo=-1;g.k.NF=!0;g.k.Yk=!1;g.k.Gw=0;g.k.Tt=null;var kHa={},H6={};g.k=E6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.nQ=function(a){a=a.target;var b=this.Tt;b&&3==Q6(a)?b.SC():this.MG(a)};
g.k.MG=function(a){try{if(a==this.Zd)a:{var b=Q6(this.Zd),c=this.Zd.I,d=this.Zd.getStatus();if(g.ye&&!g.ae(10)||g.Ae&&!g.$d("420+")){if(4>b)break a}else if(3>b||3==b&&!g.rg&&!S6(this.Zd))break a;this.Yk||4!=b||7==c||(8==c||0>=d?this.u.rh(3):this.u.rh(2));M6(this);var e=this.Zd.getStatus();this.Vo=e;var f=S6(this.Zd);(this.Ch=200==e)?(4==b&&J6(this),this.I?(lHa(this,b,f),g.rg&&this.Ch&&3==b&&(this.D.ua(this.C,"tick",this.hQ),this.C.start())):I6(this,f),this.Ch&&!this.Yk&&(4==b?this.u.gs(this):(this.Ch=
!1,G6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.bk=3,C6(13)):(this.bk=0,C6(14)),J6(this),K6(this))}}catch(h){this.Zd&&S6(this.Zd)}finally{}};
g.k.hQ=function(){var a=Q6(this.Zd),b=S6(this.Zd);this.Eq<b.length&&(M6(this),lHa(this,a,b),this.Ch&&4!=a&&G6(this))};
g.k.BP=function(a){A6((0,g.z)(this.AP,this,a),0)};
g.k.AP=function(a){this.Yk||(M6(this),I6(this,a),G6(this))};
g.k.NE=function(a){A6((0,g.z)(this.zP,this,a),0)};
g.k.zP=function(a){this.Yk||(J6(this),this.Ch=a,this.u.gs(this),this.u.rh(4))};
g.k.cancel=function(){this.Yk=!0;J6(this)};
g.k.NP=function(){this.Un=null;var a=g.A();0<=a-this.pz?(2!=this.On&&this.u.rh(3),J6(this),this.bk=2,C6(18),K6(this)):pHa(this,this.pz-a)};
g.k.getLastError=function(){return this.bk};g.Ya(O6,g.im);var wHa=/^https?$/i,kJa=["POST","PUT"];g.k=O6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.N+"; newUri="+a);b=b?b.toUpperCase():"GET";this.N=a;this.D="";this.I=0;this.ra=b;this.fa=!1;this.B=!0;this.u=this.ba?gHa(this.ba):gHa(T8);this.Y=this.ba?this.ba.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.BE,this);try{d6(R6(this,"Opening Xhr")),this.ha=!0,this.u.open(b,String(a),!0),this.ha=!1}catch(f){d6(R6(this,"Error opening Xhr: "+f.message));vHa(this,f);return}a=
c||"";var e=this.headers.clone();d&&FGa(d,function(f,h){e.set(h,f)});
d=g.jb(e.tg(),tHa);c=g.v.FormData&&a instanceof g.v.FormData;!g.nb(kJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.za&&(this.u.responseType=this.za);"withCredentials"in this.u&&this.u.withCredentials!==this.da&&(this.u.withCredentials=this.da);try{yHa(this),0<this.K&&(this.X=sHa(this.u),d6(R6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.UB,this)):this.V=g.Um(this.UB,this.K,this)),d6(R6(this,"Sending request")),this.P=!0,this.u.send(a),this.P=!1}catch(f){d6(R6(this,"Send error: "+f.message)),vHa(this,f)}};
g.k.UB=function(){"undefined"!=typeof g.$0&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,R6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.B&&(R6(this,"Aborting"),this.B=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.k.aa=function(){this.u&&(this.B&&(this.B=!1,this.F=!0,this.u.abort(),this.F=!1),P6(this,!0));O6.gd.aa.call(this)};
g.k.BE=function(){this.la()||(this.ha||this.P||this.F?xHa(this):this.KO())};
g.k.KO=function(){xHa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<Q6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=zHa.prototype;g.k.Ew=null;g.k.Qf=null;g.k.Ut=!1;g.k.TB=null;g.k.Er=null;g.k.ix=null;g.k.Fw=null;g.k.Da=null;g.k.cj=-1;g.k.Uo=null;g.k.po=null;g.k.connect=function(a){this.Fw=a;a=T6(this.u,null,this.Fw);C6(3);this.TB=g.A();var b=this.u.K;null!=b?(this.Uo=b[0],(this.po=b[1])?(this.Da=1,AHa(this)):(this.Da=2,V6(this))):(b6(a,"MODE","init"),this.Qf=new E6(this,void 0,void 0,void 0),this.Qf.xl=this.Ew,F6(this.Qf,a,!1,null,!0),this.Da=0)};
g.k.PH=function(a){if(a)this.Da=2,V6(this);else{C6(4);var b=this.u;b.ai=b.Qj.cj;b7(b,9)}a&&this.rh(2)};
g.k.Rv=function(a){return this.u.Rv(a)};
g.k.abort=function(){this.Qf&&(this.Qf.cancel(),this.Qf=null);this.cj=-1};
g.k.SB=function(){return!1};
g.k.FE=function(a,b){this.cj=a.Vo;if(0==this.Da)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.ai=this.cj;b7(c,2);return}this.Uo=c[0];this.po=c[1]}else c=this.u,c.ai=this.cj,b7(c,2);else if(2==this.Da)if(this.Ut)C6(7),this.ix=g.A();else if("11111"==b){if(C6(6),this.Ut=!0,this.Er=g.A(),c=this.Er-this.TB,!g.ye||g.ae(10)||500>c)this.cj=200,this.Qf.cancel(),C6(12),U6(this.u,this,!0)}else C6(8),this.Er=this.ix=g.A(),this.Ut=!1};
g.k.gs=function(){this.cj=this.Qf.Vo;if(this.Qf.Ch)0==this.Da?this.po?(this.Da=1,AHa(this)):(this.Da=2,V6(this)):2==this.Da&&((!g.ye||g.ae(10)?!this.Ut:200>this.ix-this.Er)?(C6(11),U6(this.u,this,!1)):(C6(12),U6(this.u,this,!0)));else{0==this.Da?C6(9):2==this.Da&&C6(10);var a=this.u;this.Qf.getLastError();a.ai=this.cj;b7(a,2)}};
g.k.kq=function(){return this.u.kq()};
g.k.isActive=function(){return this.u.isActive()};
g.k.rh=function(a){this.u.rh(a)};g.k=W6.prototype;g.k.Pm=null;g.k.Io=null;g.k.Gf=null;g.k.wd=null;g.k.Dw=null;g.k.Gr=null;g.k.xA=null;g.k.ds=null;g.k.Gp=0;g.k.hM=0;g.k.Se=null;g.k.Uj=null;g.k.Oi=null;g.k.il=null;g.k.Qj=null;g.k.zu=null;g.k.an=-1;g.k.BC=-1;g.k.ai=-1;g.k.Km=0;g.k.tm=0;g.k.Zk=8;g.Ya(CHa,g.Ll);g.Ya(DHa,g.Ll);g.k=W6.prototype;g.k.connect=function(a,b,c,d,e){C6(0);this.Dw=b;this.Io=c||{};d&&void 0!==e&&(this.Io.OSID=d,this.Io.OAID=e);this.F?(A6((0,g.z)(this.NA,this,a),100),HHa(this)):this.NA(a)};
g.k.NA=function(a){this.Qj=new zHa(this);this.Qj.Ew=this.Pm;this.Qj.B=this.D;this.Qj.connect(a)};
g.k.SB=function(){return 0==this.Da};
g.k.ME=function(a){this.Uj=null;KHa(this,a)};
g.k.LE=function(){this.Oi=null;this.wd=new E6(this,this.B,"rpc",this.I);this.wd.xl=this.Pm;this.wd.Gw=0;var a=this.xA.clone();$5(a,"RID","rpc");$5(a,"SID",this.B);$5(a,"CI",this.zu?"0":"1");$5(a,"AID",this.an);X6(this,a);if(!g.ye||g.ae(10))$5(a,"TYPE","xmlhttp"),F6(this.wd,a,!0,this.ds,!1);else{$5(a,"TYPE","html");var b=this.wd,c=!!this.ds;b.On=3;b.Mj=a6(a.clone());oHa(b,c)}};
g.k.FE=function(a,b){if(0!=this.Da&&(this.wd==a||this.Gf==a))if(this.ai=a.Vo,this.Gf==a&&3==this.Da)if(7<this.Zk){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Oi){if(this.wd)if(this.wd.Hn+3E3<this.Gf.Hn)Z6(this),this.wd.cancel(),this.wd=null;else break a;a7(this);C6(19)}}else this.BC=c[1],0<this.BC-this.an&&37500>c[2]&&this.zu&&0==this.tm&&!this.il&&(this.il=A6((0,g.z)(this.MM,this),6E3));else b7(this,11)}else b!=jJa.DS.u&&b7(this,11);else if(this.wd==
a&&Z6(this),!g.rc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.an=e[0];e=e[1];2==this.Da?"c"==e[0]?(this.B=e[1],this.ds=e[2],e=e[3],null!=e?this.Zk=e:this.Zk=6,this.Da=3,this.Se&&this.Se.JA(),this.xA=T6(this,this.kq()?this.ds:null,this.Dw),LHa(this)):"stop"==e[0]&&b7(this,7):3==this.Da&&("stop"==e[0]?b7(this,7):"noop"!=e[0]&&this.Se&&this.Se.IA(e),this.tm=0)}}};
g.k.MM=function(){null!=this.il&&(this.il=null,this.wd.cancel(),this.wd=null,a7(this),C6(20))};
g.k.gs=function(a){if(this.wd==a){Z6(this);this.wd=null;var b=2}else if(this.Gf==a)this.Gf=null,b=1;else return;this.ai=a.Vo;if(0!=this.Da)if(a.Ch)1==b?(b=B6,b.dispatchEvent(new CHa(b,a.Vl?a.Vl.length:0,g.A()-a.Hn,this.Km)),Y6(this),this.C.length=0):LHa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ai)){if(d=1==b)this.Gf||this.Uj||1==this.Da||2<=this.Km?d=!1:(this.Uj=A6((0,g.z)(this.ME,this,a),MHa(this,this.Km)),this.Km++,d=!0);d=!(d||2==b&&a7(this))}if(d)switch(c){case 1:b7(this,
5);break;case 4:b7(this,10);break;case 3:b7(this,6);break;case 7:b7(this,12);break;default:b7(this,2)}}};
g.k.lI=function(a){if(!g.nb(arguments,this.Da))throw Error("Unexpected channel state: "+this.Da);};
g.k.TQ=function(a){a?C6(2):(C6(1),NHa(this,8))};
g.k.Rv=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.da=!1;return a};
g.k.isActive=function(){return!!this.Se&&this.Se.isActive(this)};
g.k.rh=function(a){var b=B6;b.dispatchEvent(new DHa(b,a))};
g.k.kq=function(){return!(!g.ye||g.ae(10))};
g.k=OHa.prototype;g.k.JA=function(){};
g.k.IA=function(){};
g.k.HA=function(){};
g.k.Fv=function(){};
g.k.tB=function(){return{}};
g.k.isActive=function(){return!0};g.k=PHa.prototype;g.k.isEmpty=function(){return g.ob(this.u)&&g.ob(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.nb(this.u,a)||g.nb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.xAa)(b,a);0<=c?(g.qb(b,c),b=!0):b=!1;return b||g.rb(this.B,a)};
g.k.jf=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Ya(c7,g.B);g.k=c7.prototype;g.k.uP=function(){this.We=Math.min(3E5,2*this.We);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.We+15E3*Math.random();this.u.vb(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.We=5E3};g.Ya(d7,OHa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.tk=function(a){return this.C.yl(a)};
g.k.W=function(a,b){return this.C.W.apply(this.C,arguments)};
g.k.dispose=function(){this.Ld||(this.Ld=!0,g.eg(this.C),SHa(this),g.eg(this.B),this.B=null,this.X=function(){return""})};
g.k.la=function(){return this.Ld};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.Da){this.N="";this.B.stop();this.F=a||null;this.D=b||0;a=this.V+"/test";b=this.V+"/bind";var d=new W6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Y),e=this.u;e&&(e.Se=null);d.Se=this;this.u=d;e7(this);e?this.u.connect(a,b,this.I,e.B,e.an):c?this.u.connect(a,b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.B.isActive()||2==(this.u?this.u.Da:0)?this.K.push(c):f7(this)&&(e7(this),IHa(this.u,c))};
g.k.JA=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)IHa(this.u,a[b])}this.W("handlerOpened")};
g.k.HA=function(a){var b=2==a&&401==this.u.ai;4==a||b||this.B.start();this.W("handlerError",a)};
g.k.Fv=function(a){if(!this.B.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.tB=function(){var a={v:2};this.N&&(a.gsessionid=this.N);0!=this.D&&(a.ui=""+this.D);0!=this.P&&(a.ui=""+this.P);this.F&&g.bc(a,this.F);return a};
g.k.IA=function(a){"S"==a[0]?this.N=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),GHa(this.u)):this.W("handlerMessage",new QHa(a[0],a[1]))};
g.k.zQ=function(){this.B.isActive();var a=this.u,b=0;a.wd&&b++;a.Gf&&b++;0==b&&this.connect(this.F,this.D)};g7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.F=function(a){a(Error("request timed out"))};var $Ha=g.A(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Ya(o7,g.P);o7.prototype.Xf=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.I,a)};g.u(p7,g.P);g.k=p7.prototype;g.k.start=function(){!this.u&&isNaN(this.Ua)&&this.SG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Ua)||(g.Ho(this.Ua),this.Ua=NaN)};
g.k.aa=function(){this.stop();g.P.prototype.aa.call(this)};
g.k.SG=function(){this.Ua=NaN;this.u=g.oq(h7(this.I,"/pairing/get_screen"),{method:"POST",Zb:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.yR,this),onError:(0,g.z)(this.xR,this),Lf:(0,g.z)(this.zR,this)})};
g.k.yR=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.W("pairingComplete",new g6(c))};
g.k.xR=function(a){this.u=null;a.status&&404==a.status?this.B>=lJa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=lJa[this.B],this.Ua=g.Fo((0,g.z)(this.SG,this),a),this.B++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.zR=function(){this.u=null;this.W("pairingFailed",Error("Server not responding"))};
var lJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ya(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.W("screenChange");!g.Qs("yt-remote-lounge-token-expiration")&&dIa(this);g.Ho(this.u);this.u=g.Fo((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);aIa(this,a);s7(this,!1);this.W("screenChange");b(a);a.token||dIa(this)};
g.k.remove=function(a,b){var c=q7(this);cIa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.xu=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.aa=function(){g.Ho(this.u);r7.gd.aa.call(this)};
g.k.ZI=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.I,"Missed "+b+" lounge tokens.")};
g.k.YI=function(a){k7(this.I,"Requesting lounge tokens failed: "+a)};g.u(u7,g.P);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.Qs("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?w7(this):(this.D=g.A()+3E5,g.Ps("yt-remote-fast-check-period",this.D),this.qy())};
g.k.isEmpty=function(){return g.Wb(this.u)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.I(),b=g.Kb(this.u,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.aa=function(){g.Ho(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.P.prototype.aa.call(this)};
g.k.qy=function(){g.Ho(this.C);this.C=NaN;this.B&&this.B.abort();var a=gIa(this);if(c6(a)){var b=h7(this.F,"/pairing/get_screen_availability");this.B=i7(this.F,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.fP,this,a),(0,g.z)(this.eP,this))}else v7(this,{}),w7(this)};
g.k.fP=function(a,b){this.B=null;var c=g.Qb(gIa(this));if(g.Db(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.Xc("Changing Screen set during request."),this.qy()};
g.k.eP=function(a){this.Xc("Screen availability failed: "+a);this.B=null;w7(this)};
g.k.Xc=function(a){k7("OnlineScreenService",a)};g.Ya(x7,o7);g.k=x7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.W("screenChange"),this.u.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.xu=function(a,b,c,d){this.B.contains(a)?this.B.xu(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.I,a),d(Error(a)))};
g.k.Xf=function(a){return a?this.screens:g.tb(this.screens,g.Ke(this.C,function(b){return!this.contains(b)},this))};
g.k.TG=function(){return g.Ke(this.Xf(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.UG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.eg(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.eg(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.BR=function(a,b,c,d){g.oq(h7(this.F,"/pairing/get_screen"),{method:"POST",Zb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new g6(f.screen||{});if(!h.name||kIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);kIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
Lf:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.aa=function(){g.eg(this.B);g.eg(this.u);x7.gd.aa.call(this)};
g.k.gJ=function(){lIa(this);this.W("screenChange");this.u.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Ya(A7,g.P);g.k=A7.prototype;g.k.getScreen=function(){return this.K};
g.k.Jt=function(a){this.K=a;this.W("sessionScreen",this.K)};
g.k.fg=function(a){this.la()||(a&&B7(this,""+a),this.K=null,this.W("sessionScreen",null))};
g.k.info=function(a){k7(this.Y,a)};
g.k.WG=function(){return null};
g.k.By=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.aa=function(){this.By("");A7.gd.aa.call(this)};g.u(C7,A7);g.k=C7.prototype;g.k.Ay=function(a){if(this.B){if(this.B==a)return;B7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);nIa(this)};
g.k.bn=function(a){this.info("launchWithParams no-op for Cast: "+g.Fj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.fg()},this),(0,g.z)(function(){this.fg(Error("Failed to stop receiver app."))},this)):this.fg(Error("Stopping cast device witout session."))};
g.k.By=function(){};
g.k.aa=function(){this.info("disposeInternal");g.Ho(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;A7.prototype.aa.call(this)};
g.k.UP=function(a,b){if(!this.la())if(b){var c=y6(b);if(g.Sa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Fj(c));switch(d){case "mdxSessionStatus":mIa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.LB=function(a,b,c,d){jIa(this.P,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Fo((0,g.z)(this.LB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.WG=function(){return this.B};
g.k.CR=function(a){this.la()||a||(B7(this,"Cast session died."),this.fg())};g.u(D7,A7);g.k=D7.prototype;g.k.Ay=function(a){this.C=a;this.C.addUpdateListener(this.X)};
g.k.bn=function(a){this.V=a;this.F()};
g.k.stop=function(){this.B();this.B=g.Oa;g.Ho(this.D);this.C?this.C.stop((0,g.z)(this.fg,this,null),(0,g.z)(this.fg,this,"Failed to stop DIAL device.")):this.fg()};
g.k.aa=function(){this.B();this.B=g.Oa;g.Ho(this.D);this.C&&this.C.removeUpdateListener(this.X);this.C=null;A7.prototype.aa.call(this)};
g.k.FR=function(a){this.la()||a||(B7(this,"DIAL session died."),this.B(),this.B=g.Oa,this.fg())};
g.k.Qw=function(a){this.N=k6();if(this.V){var b=new chrome.cast.DialLaunchResponse(!0,pIa(this));a(b);oIa(this)}else this.F=(0,g.z)(function(){g.Ho(this.D);this.F=g.Oa;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,pIa(this));a(c);oIa(this)},this),this.D=g.Fo((0,g.z)(function(){this.F()},this),100)};
g.k.xJ=function(a,b,c){jIa(this.P,this.I.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Jt(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Qw(b,c)},this),(0,g.z)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.Qw(b,c)},this))};g.u(E7,A7);E7.prototype.stop=function(){this.fg()};
E7.prototype.Ay=function(){};
E7.prototype.bn=function(){g.Ho(this.B);this.B=NaN;var a=m6(this.P.Xf(),this.u.label);a?this.Jt(a):this.fg(Error("No such screen"))};
E7.prototype.aa=function(){g.Ho(this.B);this.B=NaN;A7.prototype.aa.call(this)};g.u(F7,g.P);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.P||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.PO,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.HE,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.mN,this);chrome.cast.initialize(c,(0,g.z)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.D),XHa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.VG,this)),this.C=rIa(this),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(h){this.Xc("Failed to set initial custom receivers: "+g.Fj(h))},this)),this.W("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.z)(function(h){this.Xc("Failed to initialize API: "+g.Fj(h));
b(!1)},this))};
g.k.FQ=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.u.u.friendlyName),I7(this,null)}if(a&&b){if(!this.u){c=m6(this.B.Xf(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=qIa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.Oa,(0,g.z)(function(e){this.Xc("Failed to set initial custom receivers: "+g.Fj(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.B,d),!0)}this.u.By(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.GQ=function(a){this.la()?this.Xc("Setting connection data on disposed cast v2"):this.u?this.u.bn(a):this.Xc("Setting connection data without a session")};
g.k.ER=function(){this.la()?this.Xc("Stopping session on disposed cast v2"):this.u?(this.u.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.HE,this),(0,g.z)(this.hP,this))};
g.k.aa=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.VG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=UHa,b=g.Na("yt.mdx.remote.debug.handlers_");g.rb(b||[],a);g.eg(this.u);g.P.prototype.aa.call(this)};
g.k.Xc=function(a){k7("Controller",a)};
g.k.JE=function(a,b){this.u==a&&(b||I7(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.LO=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.W("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.B,a,this.I));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.B,a));break;default:this.Xc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Xc("Stopping receiver w/o session: "+a.friendlyName)}else this.Xc("onReceiverAction_ called without receiver.")};
g.k.mN=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Xc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Xc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return G7("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Xc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.B,b,this.I))}b=this.u;b.I=a;return b.I.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.xJ,b,(b.I.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Qw,b))};
g.k.HE=function(a){if(!this.la()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.B,b),!0);else{this.Xc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=m6(this.B.Xf(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.eg(this.u),this.u=new C7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.JE,this,this.u)),this.u.bn(null));this.u.Ay(a)}}};
g.k.DR=function(){return this.u?this.u.WG():null};
g.k.hP=function(a){this.la()||(this.Xc("Failed to estabilish a session: "+g.Fj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.PO=function(a){G7("Receiver availability updated: "+a);if(!this.la()){var b=H7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.W("yt-remote-cast2-availability-change",H7(this))}};
g.k.VG=function(){this.la()||(this.C=rIa(this),G7("Updating custom receivers: "+g.Fj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(){this.Xc("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.GQ;F7.prototype.setConnectedScreenStatus=F7.prototype.FQ;F7.prototype.stopSession=F7.prototype.ER;F7.prototype.getCastSession=F7.prototype.DR;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.bi=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.P=a.duration,this.N=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Eb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.P+V7(this):this.P};
g.k.clone=function(){return new T7(Z7(this))};g.u(a8,g.P);g.k=a8.prototype;g.k.play=function(){1==this.Da?(this.u?this.u.play(null,g.Oa,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.W("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.Da?(this.u?this.u.pause(null,g.Oa,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.W("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.Da){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Eb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Oa,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.W("remotePlayerChange")}else c8(this,g.Wa(this.seekTo,a))};
g.k.stop=function(){if(1==this.Da){this.u?this.u.stop(null,g.Oa,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.W("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.Da){var c=b8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Xc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Xc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Wa(this.setVolume,a,b))};
g.k.QG=function(a,b){if(1==this.Da){var c=b8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Fj(b.style),g.bc(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Wa(this.QG,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.Da){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Wa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Fj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.Pt=function(a,b){if(1==this.Da){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Wa(this.Pt,a,b))};
g.k.nextVideo=function(a,b){if(1==this.Da){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Wa(this.nextVideo,a,b))};
g.k.aB=function(){1==this.Da?f8(this,"dismissAutoplay"):c8(this,this.aB)};
g.k.dispose=function(){if(3!=this.Da){var a=this.Da;this.Da=3;this.W("proxyStateChange",a,this.Da)}g.P.prototype.dispose.call(this)};
g.k.aa=function(){EIa(this);this.C=null;this.D.clear();$7(this,null);g.P.prototype.aa.call(this)};
g.k.sz=function(a){if((a!=this.Da||2==a)&&3!=this.Da&&0!=a){var b=this.Da;this.Da=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.ob(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.HO=function(a,b){this.W(a,b)};
g.k.WM=function(a){if(!a)this.Ip(null),$7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Ip=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),FIa(this),this.W("remotePlayerChange")};
g.k.VM=function(a){a?(FIa(this),this.W("remotePlayerChange")):this.Ip(null)};
g.k.Ty=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.eN=function(){var a=BIa();a&&$7(this,a)};
g.k.Xc=function(a){k7("CP",a)};g.u(h8,g.P);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Cb.listId=c);this.Cb.videoId=d;this.Cb.index=h||0;this.Cb.state=3;W7(this.Cb,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Fj(l));this.u.connect({method:"setPlaylist",
params:g.Fj(l)},a,RGa())}else i8("Connecting without params"),this.u.connect({},a,RGa());HIa(this)};
g.k.dispose=function(){this.la()||(this.W("beforeDispose"),j8(this,3));g.P.prototype.dispose.call(this)};
g.k.aa=function(){k8(this);m8(this);l8(this);g.Ho(this.K);this.K=NaN;g.Ho(this.P);this.P=NaN;this.C=null;g.dp(this.Y);this.Y.length=0;this.u.dispose();g.P.prototype.aa.call(this);this.D=this.I=this.B=this.Cb=this.u=null};
g.k.SI=function(){this.Fm(2)};
g.k.aN=function(){i8("Channel opened");this.X&&(this.X=!1,l8(this),this.V=g.Fo((0,g.z)(function(){i8("Timing out waiting for a screen.");this.Fm(1)},this),15E3));
VGa(RHa(this.u),this.ba)};
g.k.XM=function(){i8("Channel closed");isNaN(this.F)?r6(!0):r6();this.dispose()};
g.k.YM=function(a){r6();isNaN(this.Qo())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.X=!0,i8("Channel error: "+a+" with reconnection in "+this.Qo()+" ms"),j8(this,2))};
g.k.ZM=function(a){a.params?i8("Received: action="+a.action+", params="+g.Fj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.B=g.Pc(a,function(c){return new f6(c)});
a=!!g.jb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
KIa(this,a);break;case "loungeScreenDisconnected":g.sb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
KIa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.jb(this.B,function(c){return b?c.id==b.id:!1})||BGa(this.B,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.sb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":MIa(this,a);break;case "nowPlaying":OIa(this,a);break;case "onStateChange":NIa(this,a);break;case "onAdStateChange":PIa(this,a);break;case "onVolumeChanged":QIa(this,a);break;case "onSubtitlesTrackChanged":LIa(this,a);break;case "nowAutoplaying":RIa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.W("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.W("autoplayModeChange",this.D);"DISABLED"==this.D&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":SIa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.vQ=function(){if(this.C){var a=this.C;this.C=null;this.Cb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.II=function(){var a=3;this.la()||(a=0,isNaN(this.Qo())?f7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Fm=function(a){i8("Disconnecting with "+a);k8(this);this.W("beforeDisconnect",a);1==a&&r6();SHa(this.u,a);this.dispose()};
g.k.GI=function(){var a=this.Cb;this.C&&(a=this.Cb.clone(),Y7(a,this.C,a.index));return Z7(a)};
g.k.HQ=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.Cb.videoId&&(this.C=b.videoId,g.Ho(this.K),this.K=g.Fo((0,g.z)(this.vQ,this),5E3));var c=[];this.Cb.listId==b.listId&&this.Cb.videoId==b.videoId&&this.Cb.index==b.index||c.push("remoteQueueChange");this.Cb.playerState==b.playerState&&this.Cb.volume==b.volume&&this.Cb.muted==b.muted&&X7(this.Cb)==X7(b)&&g.Fj(this.Cb.u)==g.Fj(b.u)||c.push("remotePlayerChange");this.Cb.reset(a);g.Gb(c,function(d){this.W(d)},this)};
g.k.JB=function(){var a=this.u.I.id,b=g.jb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Qo=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.uI=function(){return this.D||"UNSUPPORTED"};
g.k.vI=function(){return this.I||""};
g.k.wR=function(){if(!isNaN(this.Qo())){var a=this.u.B;g.tn(a.u);a.start()}};
g.k.DQ=function(a,b){n8(this,a,b);JIa(this)};
g.k.PG=function(){var a=g.wq("SID","")||"",b=g.wq("SAPISID","")||"",c=g.wq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.qf(g.Ve(a),2);b=g.qf(g.Ve(b),2);c=g.qf(g.Ve(c),2);return g.qf(g.Ve(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.tk;h8.prototype.getProxyState=h8.prototype.II;h8.prototype.disconnect=h8.prototype.Fm;h8.prototype.getPlayerContextData=h8.prototype.GI;h8.prototype.setPlayerContextData=h8.prototype.HQ;h8.prototype.getOtherConnectedRemoteId=h8.prototype.JB;h8.prototype.getReconnectTimeout=h8.prototype.Qo;h8.prototype.getAutoplayMode=h8.prototype.uI;h8.prototype.getAutoplayVideoId=h8.prototype.vI;h8.prototype.reconnect=h8.prototype.wR;
h8.prototype.sendMessage=h8.prototype.DQ;h8.prototype.getXsrfToken=h8.prototype.PG;g.u(o8,o7);g.k=o8.prototype;g.k.Xf=function(a){return this.Ue.$_gs(a)};
g.k.contains=function(a){return!!this.Ue.$_c(a)};
g.k.get=function(a){return this.Ue.$_g(a)};
g.k.start=function(){this.Ue.$_st()};
g.k.add=function(a,b,c){this.Ue.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ue.$_r(a,b,c)};
g.k.xu=function(a,b,c,d){this.Ue.$_un(a,b,c,d)};
g.k.aa=function(){for(var a=0,b=this.u.length;a<b;++a)this.Ue.$_ubk(this.u[a]);this.u.length=0;this.Ue=null;o7.prototype.aa.call(this)};
g.k.AR=function(){this.W("screenChange")};
g.k.nO=function(){this.W("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.BR;x7.prototype.$_gsppc=x7.prototype.UG;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.xu;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Xf;x7.prototype.$_gos=x7.prototype.TG;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.tk;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.B);g.k=I8.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.u.stop();this.C.stop();this.P.stop();this.X();var a=this.sb;a.unsubscribe("proxyStateChange",this.EE,this);a.unsubscribe("remotePlayerChange",this.Np,this);a.unsubscribe("remoteQueueChange",this.Kt,this);a.unsubscribe("previousNextChange",this.AE,this);a.unsubscribe("nowAutoplaying",this.vE,this);a.unsubscribe("autoplayDismissed",this.WD,this);this.sb=this.B=null};
g.k.jD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.sb.Da)if(J8(this)){if(!b8(this.sb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.sb).Eb()?this.sb.pause():this.sb.play();break;case "control_play":this.sb.play();break;case "control_pause":this.sb.pause();break;case "control_seek":this.K.SC(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.TM=function(a){this.P.OI(a)};
g.k.fR=function(a){this.jD("control_subtitles_set_track",g.Wb(a)?null:a)};
g.k.bG=function(){var a=this.J.getOption("captions","track");g.Wb(a)||K8(this,a)};
g.k.Fc=function(a){this.B.Fc(a,this.J.getVideoData().lengthSeconds)};
g.k.lE=function(a){if(J8(this)){this.sb.unsubscribe("remotePlayerChange",this.Np,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.sb);if(b!==c.volume||a!==c.muted)this.sb.setVolume(b,a),this.N.start();this.sb.subscribe("remotePlayerChange",this.Np,this)}};
g.k.QN=function(){g.Wb(this.D)||dJa(this,this.D);this.F=!1};
g.k.EE=function(a,b){this.C.stop();2===b&&this.YF()};
g.k.Np=function(){if(J8(this)){this.u.stop();var a=b8(this.sb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.ie=1;break;case 1082:case 1083:this.B.ie=0;break;default:this.B.ie=-1}switch(a.playerState){case 1081:case 1:this.Jd(new g.XK(8));this.XF();break;case 1085:case 3:this.Jd(new g.XK(9));break;case 1083:case 0:this.Jd(new g.XK(2));this.K.stop();this.Fc(this.J.getVideoData().lengthSeconds);break;case 1084:this.Jd(new g.XK(4));break;case 2:this.Jd(new g.XK(4));this.Fc(X7(a));
break;case -1:this.Jd(new g.XK(64));break;case -1E3:this.Jd(new g.XK(128,{errorCode:"mdx.remoteerror",errorMessage:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=b8(this.sb).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.D=a,dJa(this,a));a=b8(this.sb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.N.isActive()||this.AG()}else cJa(this)};
g.k.AE=function(){this.J.W("mdxpreviousnextchange")};
g.k.Kt=function(){J8(this)||cJa(this)};
g.k.vE=function(a){isNaN(a)||this.J.W("mdxnowautoplaying",a)};
g.k.WD=function(){this.J.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.sb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.sb).playerState?L8(this,a):b&&this.sb.seekTo(a)};
g.k.AG=function(){if(J8(this)){var a=b8(this.sb);this.events.Db(this.V);a.muted?this.J.mute():this.J.unMute();this.J.setVolume(a.volume);this.V=this.events.R(this.J,"onVolumeChange",this.lE)}};
g.k.XF=function(){this.u.stop();if(!this.sb.la()){var a=b8(this.sb);a.Eb()&&this.Jd(new g.XK(8));this.Fc(X7(a));this.u.start()}};
g.k.YF=function(){this.C.stop();this.u.stop();var a=this.sb.C.getReconnectTimeout();2==this.sb.Da&&!isNaN(a)&&this.C.start()};
g.k.Jd=function(a){this.C.stop();var b=this.I;if(!g.bL(b,a)){var c=g.T(a,2);c!==g.T(this.I,2)&&g.t0(this.J.app,c);this.I=a;fJa(this.B,b,a)}};g.u(M8,g.V);M8.prototype.qc=function(){this.u.show()};
M8.prototype.fb=function(){this.u.hide()};
M8.prototype.B=function(){g.oK("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){e6("mdx-manual-pairing-popup-ok");this.fb()};g.u(N8,g.V);N8.prototype.qc=function(){this.u.show()};
N8.prototype.fb=function(){this.u.hide()};
N8.prototype.B=function(){e6("mdx-privacy-popup-cancel");this.fb()};
N8.prototype.C=function(){e6("mdx-privacy-popup-confirm");this.fb()};g.u(O8,g.V);O8.prototype.B=function(a){eJa(this,a.state)};g.u(P8,g.HZ);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Bk=g.Hb(a,this.u,this),g.IZ(this,g.Pc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.yc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.nh=function(a){return"cast-selector-receiver"===a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.Bk[a].name};
P8.prototype.ye=function(a){g.HZ.prototype.ye.call(this,a);this.J.setOption("remote","currentReceiver",this.Bk[a]);this.Sa.fb()};g.u(Q8,g.sS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.PB(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script")};XIa(b,a);this.subscriptions.push(g.No("yt-remote-before-disconnect",this.RM,this));this.subscriptions.push(g.No("yt-remote-connection-change",this.QO,this));this.subscriptions.push(g.No("yt-remote-receiver-availability-change",this.CE,this));this.subscriptions.push(g.No("yt-remote-auto-connect",this.OO,this));this.subscriptions.push(g.No("yt-remote-receiver-resumed",
this.NO,this));this.subscriptions.push(g.No("mdx-privacy-popup-confirm",this.lQ,this));this.subscriptions.push(g.No("mdx-privacy-popup-cancel",this.kQ,this));this.subscriptions.push(g.No("mdx-manual-pairing-popup-ok",this.MJ,this));this.CE()};
g.k.load=function(){this.player.cancelPlayback();g.sS.prototype.load.call(this);this.Oh=new I8(this,this.player,this.sb);var a=(a=bJa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Fc(a);fJa(this,this.Ac,this.Ac);g.B0(this.player.app,6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Sj=this.kh;g.fg(this.Oh,this.sb);this.sb=this.Oh=null;g.sS.prototype.unload.call(this);g.B0(this.player.app,5);R8(this)};
g.k.aa=function(){g.Oo(this.subscriptions);g.sS.prototype.aa.call(this)};
g.k.ri=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Oh.jD.apply(this.Oh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.ie};
g.k.KI=function(){return this.loaded?this.Oh.suggestion:null};
g.k.bi=function(){return this.sb?b8(this.sb).bi:!1};
g.k.hasNext=function(){return this.sb?b8(this.sb).hasNext:!1};
g.k.Fc=function(a,b){this.CC=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.CC};
g.k.getProgressState=function(){var a=b8(this.sb),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ge():!a.isAdPlaying()&&this.player.ge(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+V7(a):a.D,isAtLiveHead:1>=(a.C?a.B+V7(a):a.B)-this.getCurrentTime(),loaded:a.N,seekableEnd:a.C?a.B+V7(a):a.B,seekableStart:0<a.F?a.F+
V7(a):a.F}};
g.k.nextVideo=function(){this.sb&&this.sb.nextVideo()};
g.k.Pt=function(){this.sb&&this.sb.Pt()};
g.k.RM=function(a){1===a&&(this.Zx=this.sb?b8(this.sb):null)};
g.k.QO=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.Sj;this.loaded&&this.unload();this.sb=a;this.Zx=null;b.key!==this.kh.key&&(this.Sj=b,this.load())}else g.eg(this.sb),this.sb=null,this.loaded&&(this.unload(),(a=this.Zx)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.CE=function(){this.Bk=[this.kh].concat(ZIa());var a=A8()||this.kh;S8(this,a);this.player.va("onMdxReceiversChange")};
g.k.OO=function(){var a=A8();S8(this,a)};
g.k.NO=function(){this.Sj=A8()};
g.k.lQ=function(){this.Pp=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.kQ=function(){this.Pp=!1;R8(this);S8(this,this.kh);this.Sj=this.kh;G8=!1;H8=null;this.player.playVideo()};
g.k.MJ=function(){this.Ps=!0;R8(this);g.Ps("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.ce=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Bk;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.Sj:this.kh;case "quickCast":return 2===this.Bk.length&&"cast-selector-receiver"===this.Bk[1].key?(b&&R7(),!0):!1}};
g.k.Ty=function(){this.sb.Ty()};
g.k.Bh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.mX.remote=Q8;})(_yt_player);
