// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYZYU99XAxfTrSNL-bnH63DbdMMVd02U',
    appId: '1:680848775067:web:731bb6f605d46278b9333e',
    messagingSenderId: '680848775067',
    projectId: 'lab11-1d226',
    authDomain: 'lab11-1d226.firebaseapp.com',
    storageBucket: 'lab11-1d226.appspot.com',
    measurementId: 'G-JRC9PPB87N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9chzKOw2_tFiebi7R2KKj4fbK-Nq6p6g',
    appId: '1:680848775067:android:e34e30e8e13bfa9fb9333e',
    messagingSenderId: '680848775067',
    projectId: 'lab11-1d226',
    storageBucket: 'lab11-1d226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHc0W8Io_yHgWblYMJfUGoYbdSN4DLDw',
    appId: '1:680848775067:ios:92c9c8b46ba0b3b8b9333e',
    messagingSenderId: '680848775067',
    projectId: 'lab11-1d226',
    storageBucket: 'lab11-1d226.appspot.com',
    iosBundleId: 'com.example.lab111',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHc0W8Io_yHgWblYMJfUGoYbdSN4DLDw',
    appId: '1:680848775067:ios:4a8f8b7b38999475b9333e',
    messagingSenderId: '680848775067',
    projectId: 'lab11-1d226',
    storageBucket: 'lab11-1d226.appspot.com',
    iosBundleId: 'com.example.lab111.RunnerTests',
  );
}
