version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./.env
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - ./.env
  mongodb:
    image: mongo:latest
    volumes:
      - C:/data/db:/data/db
    ports:
      - "27017:27017"